// Shared colour palette. One character per colour so sprites can be drawn as
// text maps. Spooky purples and night blues, with warm cartoon accents.

export const C = {
    ink: '#1a1423',
    black: '#000000',
    white: '#ffffff',
    grey: '#9a98ad',
    greyLight: '#c9c7da',
    greyDark: '#64627a',
    pink: '#ff9fb5',
    pinkDark: '#d96a8a',
    yellow: '#ffd34d',
    yellowDark: '#e0a020',
    yellowLight: '#fff2a0',
    orange: '#ff8a1f',
    brown: '#7a4b2a',
    brownDark: '#4e2f1a',
    brownLight: '#a8693a',
    tan: '#d9a066',
    red: '#e83b3b',
    redDark: '#9c1f2e',
    purpleDark: '#2a1d45',
    purple: '#4b3478',
    purpleLight: '#7a5cb8',
    lavender: '#b49be0',
    blue: '#3b6cc4',
    blueDark: '#24447a',
    blueLight: '#6e98e0',
    cyan: '#8fe3ff',
    green: '#5ee05e',
    greenDark: '#2e8a3e',
    silver: '#d0d0dc',
    steel: '#7d7d8f',
    goo: '#120f1c',
    gooShine: '#4d4766',
    night: '#150d24',
    moon: '#fff6d8',
};

export const PALETTE: Record<string, string> = {
    k: C.ink,
    K: C.black,
    w: C.white,
    g: C.grey,
    G: C.greyLight,
    d: C.greyDark,
    p: C.pink,
    P: C.pinkDark,
    y: C.yellow,
    Y: C.yellowDark,
    h: C.yellowLight,
    o: C.orange,
    b: C.brown,
    B: C.brownDark,
    n: C.brownLight,
    t: C.tan,
    r: C.red,
    R: C.redDark,
    u: C.purpleDark,
    U: C.purple,
    v: C.purpleLight,
    V: C.lavender,
    l: C.blue,
    L: C.blueDark,
    j: C.blueLight,
    c: C.cyan,
    e: C.green,
    E: C.greenDark,
    s: C.silver,
    S: C.steel,
    m: C.goo,
    x: C.gooShine,
    M: C.moon,
};
